build site:
  image: node:6
  stage: build
  tags: 
    - docker
  script:
    - npm install --progress=false
    - cd Client
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:6
  stage: test
  tags:
    - docker
  script:
    - npm install --progress=false
    - npm run unit